### ISSUE TITLE
Consider setting `MOZ_HEADLESS` env var to `1`

### ISSUE THREAD

**Issue by McSneaky** [instrumentisto/geckodriver-docker-image#3]
Without adding this environment variable every attempt to connect fails with error:
```
Error: no DISPLAY environment variable specified
1610804842426	webdriver::server	DEBUG	<- 500 Internal Server Error {"value":{"error":"unknown error","message":"Process unexpectedly closed with status 1","stacktrace":""}}
```
Not sure if it's intentional or not. Based on readme it feels like it should be headless and not require display output

**Comment by tyranron** [comment]
@McSneaky I wonder is it due to [latest 0.29.0 upgrade](https://github.com/instrumentisto/geckodriver-docker-image) or was true for previous versions too?

**Comment by McSneaky** [comment]
> @McSneaky I wonder is it due to [latest 0.29.0 upgrade](https://github.com/instrumentisto/geckodriver-docker-image) or was true for previous versions too?

Sadly no idea :neutral_face: . The day I made the issue was the first time I ever used it

**Comment by tyranron** [comment]
@McSneaky well, maybe a connection parameters should have some parameters to run in headless mode?

I don't know the webdriver specifics, but in our builds [it works OK out-of-the-box](https://github.com/instrumentisto/medea/runs/1720446281?check_suite_focus=true#step:9:21).

Also, you can always use `-e MOZ_HEADLESS=1` in `docker run` if your installation does require it.

I don't feel like it's something that should be baked into the image. But mentioning this issue in README makes sense. Would you like to submit a PR?

**Comment by McSneaky** [comment]
@tyranron Hmm, that's odd

The command I used which caused problem: `docker run --network=host instrumentisto/geckodriver`
When running it with `docker run --network=host -e MOZ_HEADLESS=1 instrumentisto/geckodriver` then everything is good

Using copy-paste of that first example in https://github.com/jonhoo/fantoccini#examples to test

I'll file in PR to mention it in readme :+1:

**Comment by tyranron** [comment]
@McSneaky yeah, the guess was right. `wasm-bindgen` [explicitly requests headless mode when creates a new WebDriver session](https://github.com/rustwasm/wasm-bindgen/blob/0.2.69/crates/cli/src/bin/wasm-bindgen-test-runner/headless.rs#L354). Seems that `fantoccini` doesn't do that out-of-the-box, but you always may [specify them explicitly via `Client::with_capabilities()`](https://docs.rs/fantoccini/0.15.0/fantoccini/struct.Client.html#method.with_capabilities).

Thanks for PR!

**Comment by McSneaky** [comment]
Aah, that's cool! Didn't know about `wasm-bindgen` :yum: 

I think the issue can be closed, since there are already 2 solutions for it in here and there's no real need to keep it open anymore
